### ISSUE TITLE
لود داینامیک ویدجت ها در pageBuilderWidget.vue

### ISSUE THREAD

**Issue by kerasus** [kerasus/alaatv-front#37]
در حال حاضر بعد از ایجاد هر ویدجت می بایست آن را در فایل 
src/components/PageBuilder/PageBuilderWidget.vue
 نیز تعریف کنیم.
می خواهیم تعریف ویدجت ها در این فایل به صورت داینامیک صورت بگیرد، به این صورت که یک مسیر را مشخص کنیم که خودش اتوماتیک تمام ویدجت های آن مسیر را شناسایی کند و به صورت اسینک داخل src/components/PageBuilder/PageBuilderWidget.vue تعریف کند.

پیش از این چند خط کد نوشته شد که کامل نبود. اما می تواند کمک کند.
از کد های زیر استفاده کنید.

import { defineAsyncComponent } from 'vue'

// https://dev.to/jakedohm_34/auto-registering-all-your-components-in-vue-3-with-vite-4884

// const ComponentContext = require.context('components/Widgets/', true, /\.vue$/i, 'lazy')

// const components = {}
// const ComponentContext = require.context(
//   'components/Widgets/',
//   true,
//   /^.*Widget\.vue$/,
//   'lazy'
// )

// async function load (components, name) {
//   components[name] = await import('components/Widgets/' + name + '.vue')
// }

// console.log('components1', components)
// ComponentContext.keys().forEach(item => {
//   const name = item.substr(2).replace('Widgets/', '').replace('.vue', '')
//   // console.log('name', name) // TestComponent1Widget
//   // console.log('item', item) // ./Widgets/TestComponent1Widget.vue
//   // components[name] = item
//   // components[name] = () => ComponentContext(item)
//   // components[name] = import(item)
//   // components[name] = await import('components/Widgets/' + name + '.vue')
//   components[name] = () => defineAsyncComponent(() => import('components/Widgets/' + name + '.vue'))
//   // load(components, name)
// })

// console.log('components2', components)

// const components = {}

// import TestComponent1widget from 'components/Widgets/TestComponent1Widget.vue'
// import TestComponent2widget from 'components/Widgets/TestComponent2Widget.vue'

**Comment by Archer-Thane** [comment]
سلام یه فایل توضیحات با نام readme.md داخل فولدر ویدجت ها اضافه کردم که توضیح دادم چطوری باید ساخته بشه ویدجت جدید. 
در مورد یه سری از ویدجت ها تغییر نام کافی بود و انجام دادم (اگرچه ارزشش رو داره که توسط سازنده ویدجت چک بشه) ولی مثلا پروداکت الان باید تبدیل بشه به یه ویدجت که من از داخلش خبر ندارم. پروداکت یه فایل Product.vue می خواد که داخلش چند تا فایل دیگه رو مثل ProductDemos.vue رو هندل کنه.
بنظرم اگه دوستانی که ویدجت ها رو ساختن یه نگاه اجمالی بکنن که مشکلی پیش نیاد خوب می شه.

**Comment by Archer-Thane** [comment]
پیشنهادم اینه که یه پیج داشته باشیم که بتونیم توش با استفاده از پیج بیلدر فایل کانفیگش رو با یو آی بسازیم. 
این بعدا برای طراحی صفحه های جدید می تونه کمک کنه. بالاخص اگه فرد تازه به پروژه اضافه شده باشه می تونه جای options ها رو اشتباه وارد کنه.
