### ISSUE TITLE
ساخت صفحه پروفایل

### ISSUE THREAD

**Issue by kerasus** [kerasus/alaatv-front#45]
با استفاده از دیزاین ویدجتی برای صفحه پروفایل ساخته شود.
https://www.figma.com/file/VEYI4MruXFA1wSo5OcXUVK/Alaa-UI?node-id=0%3A1

**Comment by kerasus** [comment]
آدرس ویرایش اطلاعات کاربر

/api/v2/user/{id}

**Comment by Archer-Thane** [comment]
color of inputs (#aeaeae) are too pale. Can lead to misunderstanding that these inputs are disable. suggest colors are more strong.

**Comment by Archer-Thane** [comment]
there are province and city which can be added.
I've also commented in the figma

**Comment by kerasus** [comment]
https://github.com/kerasus/alaatv-front/issues/132
