### ISSUE TITLE
تیکت - صفحه مشاهده تیکت

### ISSUE THREAD

**Issue by kerasus** [kerasus/alaatv-front#48]
این صفحه مشابه صفحه موجود در پروژه لاراول ساخته شود.

**Comment by Nima0mr** [comment]
- کامپوننت message برای نمایش پیام ها آورده شده.
- صفه ی ادیت اورده شده.
- مشکلات api به اقا محمد اطلاع داده شده.
- مشکل نمایش تقویم شمسی حل شده.
- باگ های کامپ.ننت message.vue حل شده.
- پکیج مورد نیاز دارای مشکل بود و بالا نمیامد که اون هم حل شده.
- اخرین اپدیت ها در branch ticket فرستاده شده.

**Comment by Nima0mr** [comment]
حالت پیام خصوصی و صفه مشاهده از سمت کاربر بعد از درست شدن api باید بررسی شود
